namespace QuillsModManagerV2
{
    partial class QMM
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(QMM));
            this.PanelHeader = new Guna.UI2.WinForms.Guna2Panel();
            this.BtnMinimize = new Guna.UI2.WinForms.Guna2ControlBox();
            this.BtnClose = new Guna.UI2.WinForms.Guna2ControlBox();
            this.QMMEProperties = new Guna.UI2.WinForms.Guna2BorderlessForm(this.components);
            this.BtnMaximize = new Guna.UI2.WinForms.Guna2ControlBox();
            this.PanelSideBar = new Guna.UI2.WinForms.Guna2Panel();
            this.PanelProfileInfo = new Guna.UI2.WinForms.Guna2Panel();
            this.LabelCurrentProfile = new System.Windows.Forms.Label();
            this.LabelModBrowser = new System.Windows.Forms.Label();
            this.LabelModCount = new System.Windows.Forms.Label();
            this.LabelMadeBy = new System.Windows.Forms.Label();
            this.LabelVersion = new System.Windows.Forms.Label();
            this.PanelSearchBox = new Guna.UI2.WinForms.Guna2Panel();
            this.LabelSearchGlass = new System.Windows.Forms.Label();
            this.TextBoxSearch = new Guna.UI2.WinForms.Guna2TextBox();
            this.PictureBoxIcon = new System.Windows.Forms.PictureBox();
            this.BtnOpenAppdata = new Guna.UI2.WinForms.Guna2Button();
            this.BtnDeployMods = new Guna.UI2.WinForms.Guna2Button();
            this.BtnUndeployMods = new Guna.UI2.WinForms.Guna2Button();
            this.BtnStartGame = new Guna.UI2.WinForms.Guna2Button();
            this.BtnProfile = new Guna.UI2.WinForms.Guna2Button();
            this.BtnSettings = new Guna.UI2.WinForms.Guna2Button();
            this.LabelTitle = new QuillsModManagerV2.Util.Controls.CClickThroughLabel();
            this.ModBrowser = new QuillsModManagerV2.Util.Controls.ModBrowser();
            this.PanelProfileInfo.SuspendLayout();
            this.PanelSearchBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PictureBoxIcon)).BeginInit();
            this.SuspendLayout();
                                             this.PanelHeader.AccessibleName = "PanelHeader";
            this.PanelHeader.AutoSize = true;
            this.PanelHeader.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.PanelHeader.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelHeader.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelHeader.BorderThickness = 1;
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.PanelHeader.Enabled = false;
            this.PanelHeader.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.PanelHeader.Location = new System.Drawing.Point(10, 10);
            this.PanelHeader.Margin = new System.Windows.Forms.Padding(0);
            this.PanelHeader.MaximumSize = new System.Drawing.Size(0, 34);
            this.PanelHeader.MinimumSize = new System.Drawing.Size(646, 34);
            this.PanelHeader.Name = "PanelHeader";
            this.PanelHeader.Padding = new System.Windows.Forms.Padding(1);
            this.PanelHeader.Size = new System.Drawing.Size(646, 34);
            this.PanelHeader.TabIndex = 0;
                                             this.BtnMinimize.AccessibleName = "BtnMinimize";
            this.BtnMinimize.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnMinimize.Animated = true;
            this.BtnMinimize.BackColor = System.Drawing.Color.Transparent;
            this.BtnMinimize.BorderRadius = 1;
            this.BtnMinimize.ControlBoxType = Guna.UI2.WinForms.Enums.ControlBoxType.MinimizeBox;
            this.BtnMinimize.CustomizableEdges.BottomLeft = false;
            this.BtnMinimize.CustomizableEdges.BottomRight = false;
            this.BtnMinimize.CustomizableEdges.TopLeft = false;
            this.BtnMinimize.CustomizableEdges.TopRight = false;
            this.BtnMinimize.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnMinimize.DataBindings.Add(new System.Windows.Forms.Binding("IconColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnMinimize.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnMinimize.HoverState.FillColor = System.Drawing.Color.Gray;
            this.BtnMinimize.IconColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnMinimize.Location = new System.Drawing.Point(545, 11);
            this.BtnMinimize.Margin = new System.Windows.Forms.Padding(0);
            this.BtnMinimize.MaximumSize = new System.Drawing.Size(37, 32);
            this.BtnMinimize.Name = "BtnMinimize";
            this.BtnMinimize.Size = new System.Drawing.Size(37, 32);
            this.BtnMinimize.TabIndex = 0;
            this.BtnMinimize.TabStop = false;
            this.BtnMinimize.UseTransparentBackground = true;
                                             this.BtnClose.AccessibleName = "BtnClose";
            this.BtnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnClose.Animated = true;
            this.BtnClose.BackColor = System.Drawing.Color.Transparent;
            this.BtnClose.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(16)))), ((int)(((byte)(20)))));
            this.BtnClose.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnClose.CustomClick = true;
            this.BtnClose.CustomizableEdges.BottomLeft = false;
            this.BtnClose.CustomizableEdges.TopLeft = false;
            this.BtnClose.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnClose.DataBindings.Add(new System.Windows.Forms.Binding("IconColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnClose.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnClose.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnClose.HoverState.FillColor = System.Drawing.Color.Red;
            this.BtnClose.IconColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnClose.Location = new System.Drawing.Point(619, 11);
            this.BtnClose.MaximumSize = new System.Drawing.Size(37, 32);
            this.BtnClose.Name = "BtnClose";
            this.BtnClose.Size = new System.Drawing.Size(37, 32);
            this.BtnClose.TabIndex = 0;
            this.BtnClose.TabStop = false;
            this.BtnClose.UseTransparentBackground = true;
            this.BtnClose.Click += new System.EventHandler(this.BtnClose_Click);
                                             this.QMMEProperties.AnimateWindow = true;
            this.QMMEProperties.AnimationInterval = 200;
            this.QMMEProperties.BorderRadius = 24;
            this.QMMEProperties.ContainerControl = this;
            this.QMMEProperties.DockForm = false;
            this.QMMEProperties.DockIndicatorTransparencyValue = 0.6D;
            this.QMMEProperties.ShadowColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailActive;
            this.QMMEProperties.TransparentWhileDrag = true;
                                             this.BtnMaximize.AccessibleName = "BtnMaximize";
            this.BtnMaximize.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnMaximize.Animated = true;
            this.BtnMaximize.BackColor = System.Drawing.Color.Transparent;
            this.BtnMaximize.BorderRadius = 1;
            this.BtnMaximize.ControlBoxType = Guna.UI2.WinForms.Enums.ControlBoxType.MaximizeBox;
            this.BtnMaximize.CustomizableEdges.BottomLeft = false;
            this.BtnMaximize.CustomizableEdges.BottomRight = false;
            this.BtnMaximize.CustomizableEdges.TopLeft = false;
            this.BtnMaximize.CustomizableEdges.TopRight = false;
            this.BtnMaximize.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnMaximize.DataBindings.Add(new System.Windows.Forms.Binding("IconColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnMaximize.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnMaximize.HoverState.FillColor = System.Drawing.Color.Gray;
            this.BtnMaximize.IconColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnMaximize.Location = new System.Drawing.Point(582, 11);
            this.BtnMaximize.Margin = new System.Windows.Forms.Padding(0);
            this.BtnMaximize.MaximumSize = new System.Drawing.Size(37, 32);
            this.BtnMaximize.Name = "BtnMaximize";
            this.BtnMaximize.Size = new System.Drawing.Size(37, 32);
            this.BtnMaximize.TabIndex = 0;
            this.BtnMaximize.TabStop = false;
            this.BtnMaximize.UseTransparentBackground = true;
            this.BtnMaximize.Click += new System.EventHandler(this.BtnMaximize_Click);
                                             this.PanelSideBar.AccessibleName = "PanelSideBar";
            this.PanelSideBar.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.PanelSideBar.AutoSize = true;
            this.PanelSideBar.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.PanelSideBar.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelSideBar.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelSideBar.BorderThickness = 1;
            this.PanelSideBar.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelSideBar.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelSideBar.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelSideBar.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelSideBar.Enabled = false;
            this.PanelSideBar.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.PanelSideBar.Location = new System.Drawing.Point(10, 54);
            this.PanelSideBar.Margin = new System.Windows.Forms.Padding(0);
            this.PanelSideBar.MaximumSize = new System.Drawing.Size(34, 9999);
            this.PanelSideBar.MinimumSize = new System.Drawing.Size(34, 34);
            this.PanelSideBar.Name = "PanelSideBar";
            this.PanelSideBar.Padding = new System.Windows.Forms.Padding(1);
            this.PanelSideBar.Size = new System.Drawing.Size(34, 242);
            this.PanelSideBar.TabIndex = 0;
                                             this.PanelProfileInfo.AccessibleName = "PanelProfileInfo";
            this.PanelProfileInfo.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.PanelProfileInfo.AutoSize = true;
            this.PanelProfileInfo.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.PanelProfileInfo.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelProfileInfo.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelProfileInfo.BorderThickness = 1;
            this.PanelProfileInfo.Controls.Add(this.LabelCurrentProfile);
            this.PanelProfileInfo.Controls.Add(this.LabelModBrowser);
            this.PanelProfileInfo.Controls.Add(this.LabelModCount);
            this.PanelProfileInfo.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelProfileInfo.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelProfileInfo.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelProfileInfo.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelProfileInfo.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.PanelProfileInfo.Location = new System.Drawing.Point(110, 54);
            this.PanelProfileInfo.Margin = new System.Windows.Forms.Padding(0);
            this.PanelProfileInfo.MaximumSize = new System.Drawing.Size(9999, 34);
            this.PanelProfileInfo.MinimumSize = new System.Drawing.Size(34, 34);
            this.PanelProfileInfo.Name = "PanelProfileInfo";
            this.PanelProfileInfo.Padding = new System.Windows.Forms.Padding(1);
            this.PanelProfileInfo.Size = new System.Drawing.Size(446, 34);
            this.PanelProfileInfo.TabIndex = 0;
                                             this.LabelCurrentProfile.AccessibleName = "LabelCurrentProfile";
            this.LabelCurrentProfile.AutoSize = true;
            this.LabelCurrentProfile.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.LabelCurrentProfile.Cursor = System.Windows.Forms.Cursors.Hand;
            this.LabelCurrentProfile.DataBindings.Add(new System.Windows.Forms.Binding("Text", global::QuillsModManagerV2.Properties.Settings.Default, "CurrentProfile", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelCurrentProfile.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelCurrentProfile.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelCurrentProfile.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.LabelCurrentProfile.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.LabelCurrentProfile.Location = new System.Drawing.Point(7, 9);
            this.LabelCurrentProfile.Name = "LabelCurrentProfile";
            this.LabelCurrentProfile.Size = new System.Drawing.Size(56, 16);
            this.LabelCurrentProfile.TabIndex = 1;
            this.LabelCurrentProfile.Text = global::QuillsModManagerV2.Properties.Settings.Default.CurrentProfile;
            this.LabelCurrentProfile.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LabelCurrentProfile.Click += new System.EventHandler(this.LabelCurrentProfile_Click);
                                             this.LabelModBrowser.AccessibleName = "LabelModBrowser";
            this.LabelModBrowser.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.LabelModBrowser.AutoSize = true;
            this.LabelModBrowser.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.LabelModBrowser.Cursor = System.Windows.Forms.Cursors.Arrow;
            this.LabelModBrowser.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelModBrowser.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelModBrowser.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.LabelModBrowser.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.LabelModBrowser.Location = new System.Drawing.Point(181, 9);
            this.LabelModBrowser.MaximumSize = new System.Drawing.Size(100, 16);
            this.LabelModBrowser.Name = "LabelModBrowser";
            this.LabelModBrowser.Size = new System.Drawing.Size(84, 16);
            this.LabelModBrowser.TabIndex = 1;
            this.LabelModBrowser.Text = "Mod Browser";
            this.LabelModBrowser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
                                             this.LabelModCount.AccessibleName = "LabelModCount";
            this.LabelModCount.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.LabelModCount.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.LabelModCount.Cursor = System.Windows.Forms.Cursors.Arrow;
            this.LabelModCount.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelModCount.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelModCount.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.LabelModCount.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.LabelModCount.Location = new System.Drawing.Point(355, 9);
            this.LabelModCount.Name = "LabelModCount";
            this.LabelModCount.Size = new System.Drawing.Size(86, 16);
            this.LabelModCount.TabIndex = 1;
            this.LabelModCount.Text = "mod-count";
            this.LabelModCount.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
                                             this.LabelMadeBy.AccessibleName = "LabelMadeBy";
            this.LabelMadeBy.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.LabelMadeBy.AutoSize = true;
            this.LabelMadeBy.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.LabelMadeBy.Cursor = System.Windows.Forms.Cursors.Hand;
            this.LabelMadeBy.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "PlaceholderColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelMadeBy.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelMadeBy.Font = new System.Drawing.Font("Cascadia Code", 9F);
            this.LabelMadeBy.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.PlaceholderColor;
            this.LabelMadeBy.Location = new System.Drawing.Point(523, 299);
            this.LabelMadeBy.Name = "LabelMadeBy";
            this.LabelMadeBy.Size = new System.Drawing.Size(133, 16);
            this.LabelMadeBy.TabIndex = 0;
            this.LabelMadeBy.Text = "Made By Papa Quill";
            this.LabelMadeBy.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LabelMadeBy.Click += new System.EventHandler(this.LabelMadeBy_Click);
                                             this.LabelVersion.AccessibleName = "LabelVersion";
            this.LabelVersion.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.LabelVersion.AutoSize = true;
            this.LabelVersion.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.LabelVersion.Cursor = System.Windows.Forms.Cursors.Hand;
            this.LabelVersion.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "PlaceholderColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelVersion.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelVersion.Font = new System.Drawing.Font("Cascadia Code", 9F);
            this.LabelVersion.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.PlaceholderColor;
            this.LabelVersion.Location = new System.Drawing.Point(7, 299);
            this.LabelVersion.Name = "LabelVersion";
            this.LabelVersion.Size = new System.Drawing.Size(49, 16);
            this.LabelVersion.TabIndex = 0;
            this.LabelVersion.Text = global::QuillsModManagerV2.Properties.Settings.Default.Version;
            this.LabelVersion.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LabelVersion.Click += new System.EventHandler(this.LabelVersion_Click);
                                             this.PanelSearchBox.AccessibleName = "PanelSearchBox";
            this.PanelSearchBox.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.PanelSearchBox.AutoSize = true;
            this.PanelSearchBox.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.PanelSearchBox.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelSearchBox.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelSearchBox.BorderThickness = 1;
            this.PanelSearchBox.Controls.Add(this.LabelSearchGlass);
            this.PanelSearchBox.Controls.Add(this.TextBoxSearch);
            this.PanelSearchBox.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelSearchBox.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelSearchBox.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelSearchBox.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelSearchBox.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.PanelSearchBox.Location = new System.Drawing.Point(566, 54);
            this.PanelSearchBox.Margin = new System.Windows.Forms.Padding(0);
            this.PanelSearchBox.MaximumSize = new System.Drawing.Size(300, 34);
            this.PanelSearchBox.MinimumSize = new System.Drawing.Size(34, 34);
            this.PanelSearchBox.Name = "PanelSearchBox";
            this.PanelSearchBox.Padding = new System.Windows.Forms.Padding(1);
            this.PanelSearchBox.Size = new System.Drawing.Size(91, 34);
            this.PanelSearchBox.TabIndex = 0;
                                             this.LabelSearchGlass.AccessibleName = "LabelSearchGlass";
            this.LabelSearchGlass.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.LabelSearchGlass.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.LabelSearchGlass.Cursor = System.Windows.Forms.Cursors.Arrow;
            this.LabelSearchGlass.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelSearchGlass.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelSearchGlass.Font = new System.Drawing.Font("Arial", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LabelSearchGlass.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.LabelSearchGlass.Location = new System.Drawing.Point(7, 6);
            this.LabelSearchGlass.Name = "LabelSearchGlass";
            this.LabelSearchGlass.Size = new System.Drawing.Size(17, 20);
            this.LabelSearchGlass.TabIndex = 1;
            this.LabelSearchGlass.Text = "🔍︎";
            this.LabelSearchGlass.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
                                             this.TextBoxSearch.AccessibleName = "TextBoxSearch";
            this.TextBoxSearch.Animated = true;
            this.TextBoxSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.TextBoxSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.TextBoxSearch.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.TextBoxSearch.BorderThickness = 0;
            this.TextBoxSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSearch.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxSearch.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxSearch.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxSearch.DataBindings.Add(new System.Windows.Forms.Binding("PlaceholderForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "PlaceholderColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxSearch.DefaultText = "";
            this.TextBoxSearch.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.TextBoxSearch.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.TextBoxSearch.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TextBoxSearch.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TextBoxSearch.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.TextBoxSearch.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TextBoxSearch.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.TextBoxSearch.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.TextBoxSearch.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TextBoxSearch.Location = new System.Drawing.Point(24, 5);
            this.TextBoxSearch.MaxLength = 7;
            this.TextBoxSearch.Name = "TextBoxSearch";
            this.TextBoxSearch.PasswordChar = '\0';
            this.TextBoxSearch.PlaceholderForeColor = global::QuillsModManagerV2.Properties.Settings.Default.PlaceholderColor;
            this.TextBoxSearch.PlaceholderText = "Search...";
            this.TextBoxSearch.SelectedText = "";
            this.TextBoxSearch.Size = new System.Drawing.Size(60, 25);
            this.TextBoxSearch.TabIndex = 0;
            this.TextBoxSearch.TextOffset = new System.Drawing.Point(-7, 0);
            this.TextBoxSearch.WordWrap = false;
            this.TextBoxSearch.TextChanged += new System.EventHandler(this.TextBoxSearch_TextChanged);
                                             this.PictureBoxIcon.AccessibleName = "PictureBoxIcon";
            this.PictureBoxIcon.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.PictureBoxIcon.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PictureBoxIcon.Image = ((System.Drawing.Image)(resources.GetObject("PictureBoxIcon.Image")));
            this.PictureBoxIcon.Location = new System.Drawing.Point(16, 12);
            this.PictureBoxIcon.Name = "PictureBoxIcon";
            this.PictureBoxIcon.Size = new System.Drawing.Size(30, 30);
            this.PictureBoxIcon.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.PictureBoxIcon.TabIndex = 2;
            this.PictureBoxIcon.TabStop = false;
                                             this.BtnOpenAppdata.AccessibleDescription = "Open Appdata Folder";
            this.BtnOpenAppdata.AccessibleName = "BtnOpenAppdata";
            this.BtnOpenAppdata.Animated = true;
            this.BtnOpenAppdata.BackColor = System.Drawing.Color.Transparent;
            this.BtnOpenAppdata.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnOpenAppdata.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnOpenAppdata.BorderThickness = 1;
            this.BtnOpenAppdata.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnOpenAppdata.CustomizableEdges.BottomLeft = false;
            this.BtnOpenAppdata.CustomizableEdges.BottomRight = false;
            this.BtnOpenAppdata.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnOpenAppdata.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnOpenAppdata.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnOpenAppdata.DataBindings.Add(new System.Windows.Forms.Binding("PressedColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnOpenAppdata.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnOpenAppdata.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.BtnOpenAppdata.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.BtnOpenAppdata.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.BtnOpenAppdata.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnOpenAppdata.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnOpenAppdata.ForeColor = System.Drawing.Color.White;
            this.BtnOpenAppdata.Image = ((System.Drawing.Image)(resources.GetObject("BtnOpenAppdata.Image")));
            this.BtnOpenAppdata.ImageOffset = new System.Drawing.Point(1, 0);
            this.BtnOpenAppdata.ImageSize = new System.Drawing.Size(16, 16);
            this.BtnOpenAppdata.Location = new System.Drawing.Point(10, 54);
            this.BtnOpenAppdata.Name = "BtnOpenAppdata";
            this.BtnOpenAppdata.PressedColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.BtnOpenAppdata.Size = new System.Drawing.Size(34, 34);
            this.BtnOpenAppdata.TabIndex = 0;
            this.BtnOpenAppdata.UseTransparentBackground = true;
            this.BtnOpenAppdata.Click += new System.EventHandler(this.BtnOpenAppdata_Click);
            this.BtnOpenAppdata.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnDeployMods.AccessibleDescription = "Deploy Mods";
            this.BtnDeployMods.AccessibleName = "BtnDeployMods";
            this.BtnDeployMods.Animated = true;
            this.BtnDeployMods.BackColor = System.Drawing.Color.Transparent;
            this.BtnDeployMods.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnDeployMods.BorderThickness = 1;
            this.BtnDeployMods.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnDeployMods.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnDeployMods.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnDeployMods.DataBindings.Add(new System.Windows.Forms.Binding("PressedColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnDeployMods.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnDeployMods.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.BtnDeployMods.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.BtnDeployMods.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.BtnDeployMods.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnDeployMods.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnDeployMods.ForeColor = System.Drawing.Color.White;
            this.BtnDeployMods.Image = ((System.Drawing.Image)(resources.GetObject("BtnDeployMods.Image")));
            this.BtnDeployMods.Location = new System.Drawing.Point(10, 87);
            this.BtnDeployMods.Name = "BtnDeployMods";
            this.BtnDeployMods.PressedColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.BtnDeployMods.Size = new System.Drawing.Size(34, 34);
            this.BtnDeployMods.TabIndex = 0;
            this.BtnDeployMods.Click += new System.EventHandler(this.BtnDeployMods_Click);
            this.BtnDeployMods.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnUndeployMods.AccessibleDescription = "Undeploy Mods";
            this.BtnUndeployMods.AccessibleName = "BtnUndeployMods";
            this.BtnUndeployMods.Animated = true;
            this.BtnUndeployMods.BackColor = System.Drawing.Color.Transparent;
            this.BtnUndeployMods.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnUndeployMods.BorderThickness = 1;
            this.BtnUndeployMods.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnUndeployMods.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnUndeployMods.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnUndeployMods.DataBindings.Add(new System.Windows.Forms.Binding("PressedColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnUndeployMods.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnUndeployMods.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.BtnUndeployMods.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.BtnUndeployMods.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.BtnUndeployMods.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnUndeployMods.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnUndeployMods.ForeColor = System.Drawing.Color.White;
            this.BtnUndeployMods.Image = ((System.Drawing.Image)(resources.GetObject("BtnUndeployMods.Image")));
            this.BtnUndeployMods.Location = new System.Drawing.Point(10, 120);
            this.BtnUndeployMods.Name = "BtnUndeployMods";
            this.BtnUndeployMods.PressedColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.BtnUndeployMods.Size = new System.Drawing.Size(34, 34);
            this.BtnUndeployMods.TabIndex = 0;
            this.BtnUndeployMods.Click += new System.EventHandler(this.BtnUndeployMods_Click);
            this.BtnUndeployMods.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnStartGame.AccessibleDescription = "Launch Game";
            this.BtnStartGame.AccessibleName = "BtnStartGame";
            this.BtnStartGame.Animated = true;
            this.BtnStartGame.BackColor = System.Drawing.Color.Transparent;
            this.BtnStartGame.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnStartGame.BorderThickness = 1;
            this.BtnStartGame.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnStartGame.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnStartGame.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnStartGame.DataBindings.Add(new System.Windows.Forms.Binding("PressedColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnStartGame.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnStartGame.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.BtnStartGame.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.BtnStartGame.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.BtnStartGame.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnStartGame.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnStartGame.ForeColor = System.Drawing.Color.White;
            this.BtnStartGame.Image = ((System.Drawing.Image)(resources.GetObject("BtnStartGame.Image")));
            this.BtnStartGame.Location = new System.Drawing.Point(10, 153);
            this.BtnStartGame.Name = "BtnStartGame";
            this.BtnStartGame.PressedColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.BtnStartGame.Size = new System.Drawing.Size(34, 34);
            this.BtnStartGame.TabIndex = 0;
            this.BtnStartGame.Click += new System.EventHandler(this.BtnStartGame_Click);
            this.BtnStartGame.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnProfile.AccessibleDescription = "Profile Manager";
            this.BtnProfile.AccessibleName = "BtnProfile";
            this.BtnProfile.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.BtnProfile.Animated = true;
            this.BtnProfile.BackColor = System.Drawing.Color.Transparent;
            this.BtnProfile.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnProfile.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnProfile.BorderThickness = 1;
            this.BtnProfile.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnProfile.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnProfile.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnProfile.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnProfile.DataBindings.Add(new System.Windows.Forms.Binding("PressedColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailActive", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnProfile.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnProfile.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.BtnProfile.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.BtnProfile.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.BtnProfile.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.BtnProfile.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnProfile.ForeColor = System.Drawing.Color.White;
            this.BtnProfile.Image = ((System.Drawing.Image)(resources.GetObject("BtnProfile.Image")));
            this.BtnProfile.Location = new System.Drawing.Point(57, 54);
            this.BtnProfile.Name = "BtnProfile";
            this.BtnProfile.PressedColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailActive;
            this.BtnProfile.Size = new System.Drawing.Size(43, 34);
            this.BtnProfile.TabIndex = 0;
            this.BtnProfile.UseTransparentBackground = true;
            this.BtnProfile.Click += new System.EventHandler(this.LabelCurrentProfile_Click);
            this.BtnProfile.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnSettings.AccessibleDescription = "Open Settings";
            this.BtnSettings.AccessibleName = "BtnSettings";
            this.BtnSettings.Animated = true;
            this.BtnSettings.BackColor = System.Drawing.Color.Transparent;
            this.BtnSettings.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnSettings.BorderThickness = 1;
            this.BtnSettings.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnSettings.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSettings.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSettings.DataBindings.Add(new System.Windows.Forms.Binding("PressedColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSettings.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnSettings.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.BtnSettings.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.BtnSettings.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.BtnSettings.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnSettings.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnSettings.ForeColor = System.Drawing.Color.White;
            this.BtnSettings.Image = ((System.Drawing.Image)(resources.GetObject("BtnSettings.Image")));
            this.BtnSettings.ImageOffset = new System.Drawing.Point(1, 1);
            this.BtnSettings.ImageSize = new System.Drawing.Size(30, 30);
            this.BtnSettings.Location = new System.Drawing.Point(10, 186);
            this.BtnSettings.Name = "BtnSettings";
            this.BtnSettings.PressedColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.BtnSettings.Size = new System.Drawing.Size(34, 34);
            this.BtnSettings.TabIndex = 0;
            this.BtnSettings.Tag = typeof(QuillsModManagerV2.UserControls.FormSettings);
            this.BtnSettings.Click += new System.EventHandler(this.SideBarButton_Click);
            this.BtnSettings.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.LabelTitle.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.LabelTitle.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelTitle.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelTitle.Font = new System.Drawing.Font("Cascadia Code", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LabelTitle.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.LabelTitle.Location = new System.Drawing.Point(48, 16);
            this.LabelTitle.Name = "LabelTitle";
            this.LabelTitle.Size = new System.Drawing.Size(100, 23);
            this.LabelTitle.TabIndex = 1;
            this.LabelTitle.Text = "QMM / HOME";
                                             this.ModBrowser.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ModBrowser.Location = new System.Drawing.Point(57, 101);
            this.ModBrowser.MinimumSize = new System.Drawing.Size(599, 195);
            this.ModBrowser.Name = "ModBrowser";
            this.ModBrowser.Size = new System.Drawing.Size(599, 195);
            this.ModBrowser.TabIndex = 0;
                                             this.AccessibleName = "QMMV2";
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.ClientSize = new System.Drawing.Size(667, 322);
            this.Controls.Add(this.BtnProfile);
            this.Controls.Add(this.BtnSettings);
            this.Controls.Add(this.BtnStartGame);
            this.Controls.Add(this.BtnUndeployMods);
            this.Controls.Add(this.BtnDeployMods);
            this.Controls.Add(this.BtnOpenAppdata);
            this.Controls.Add(this.PictureBoxIcon);
            this.Controls.Add(this.LabelTitle);
            this.Controls.Add(this.BtnMinimize);
            this.Controls.Add(this.BtnClose);
            this.Controls.Add(this.BtnMaximize);
            this.Controls.Add(this.PanelHeader);
            this.Controls.Add(this.PanelSideBar);
            this.Controls.Add(this.PanelProfileInfo);
            this.Controls.Add(this.PanelSearchBox);
            this.Controls.Add(this.LabelMadeBy);
            this.Controls.Add(this.LabelVersion);
            this.Controls.Add(this.ModBrowser);
            this.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(667, 322);
            this.Name = "QMM";
            this.Padding = new System.Windows.Forms.Padding(10, 10, 11, 10);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "QMM HOME";
            this.DoubleClick += new System.EventHandler(this.QMM_DoubleClick);
            this.PanelProfileInfo.ResumeLayout(false);
            this.PanelProfileInfo.PerformLayout();
            this.PanelSearchBox.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PictureBoxIcon)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Guna.UI2.WinForms.Guna2Panel PanelHeader;
        private Guna.UI2.WinForms.Guna2ControlBox BtnMinimize;
        private Guna.UI2.WinForms.Guna2ControlBox BtnClose;
        private Guna.UI2.WinForms.Guna2BorderlessForm QMMEProperties;
        private Guna.UI2.WinForms.Guna2ControlBox BtnMaximize;
        private Guna.UI2.WinForms.Guna2Panel PanelSideBar;
        private Util.Controls.CClickThroughLabel LabelTitle;
        private Util.Controls.ModBrowser ModBrowser;
        private Guna.UI2.WinForms.Guna2Panel PanelProfileInfo;
        private System.Windows.Forms.Label LabelMadeBy;
        private System.Windows.Forms.Label LabelCurrentProfile;
        private System.Windows.Forms.Label LabelModCount;
        private System.Windows.Forms.Label LabelModBrowser;
        private System.Windows.Forms.Label LabelVersion;
        private Guna.UI2.WinForms.Guna2Panel PanelSearchBox;
        private Guna.UI2.WinForms.Guna2TextBox TextBoxSearch;
        private System.Windows.Forms.Label LabelSearchGlass;
        private System.Windows.Forms.PictureBox PictureBoxIcon;
        private Guna.UI2.WinForms.Guna2Button BtnOpenAppdata;
        private Guna.UI2.WinForms.Guna2Button BtnDeployMods;
        private Guna.UI2.WinForms.Guna2Button BtnUndeployMods;
        private Guna.UI2.WinForms.Guna2Button BtnStartGame;
        private Guna.UI2.WinForms.Guna2Button BtnSettings;
        private Guna.UI2.WinForms.Guna2Button BtnProfile;
    }
}

