namespace QuillsModManagerV2.UserControls
{
    partial class FormSettings
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormSettings));
            this.FormSettingsEProperties = new Guna.UI2.WinForms.Guna2BorderlessForm(this.components);
            this.ImgIcon = new System.Windows.Forms.PictureBox();
            this.BtnResetSettings = new Guna.UI2.WinForms.Guna2Button();
            this.LabelTitle = new QuillsModManagerV2.Util.Controls.CClickThroughLabel();
            this.BtnClose = new Guna.UI2.WinForms.Guna2ControlBox();
            this.PanelHeader = new Guna.UI2.WinForms.Guna2Panel();
            this.PanelBools = new Guna.UI2.WinForms.Guna2Panel();
            this.PanelContent = new System.Windows.Forms.Panel();
            this.vScroll = new QuillsModManagerV2.Util.Controls.CustomVScrollBar();
            this.PanelBody = new Guna.UI2.WinForms.Guna2Panel();
            this.BtnChooseGamePath = new Guna.UI2.WinForms.Guna2Button();
            this.BtnChooseUserDataPath = new Guna.UI2.WinForms.Guna2Button();
            this.BtnChooseModPath = new Guna.UI2.WinForms.Guna2Button();
            this.TextBoxModPath = new Guna.UI2.WinForms.Guna2TextBox();
            this.TextBoxUserDataPath = new Guna.UI2.WinForms.Guna2TextBox();
            this.TextBoxGamePath = new Guna.UI2.WinForms.Guna2TextBox();
            this.BtnTheme = new Guna.UI2.WinForms.Guna2Button();
            this.PanelThemeHeader = new Guna.UI2.WinForms.Guna2Panel();
            this.LabelThemeTitle = new System.Windows.Forms.Label();
            this.PanelTogglesHeader = new Guna.UI2.WinForms.Guna2Panel();
            this.LabelTogglesTitle = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.ImgIcon)).BeginInit();
            this.PanelBools.SuspendLayout();
            this.PanelContent.SuspendLayout();
            this.PanelBody.SuspendLayout();
            this.PanelThemeHeader.SuspendLayout();
            this.PanelTogglesHeader.SuspendLayout();
            this.SuspendLayout();
                                             this.FormSettingsEProperties.ContainerControl = this;
            this.FormSettingsEProperties.DockForm = false;
            this.FormSettingsEProperties.DockIndicatorTransparencyValue = 0.6D;
            this.FormSettingsEProperties.DragForm = false;
            this.FormSettingsEProperties.DragStartTransparencyValue = 1D;
            this.FormSettingsEProperties.ResizeForm = false;
            this.FormSettingsEProperties.ShadowColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailActive;
            this.FormSettingsEProperties.TransparentWhileDrag = true;
                                             this.ImgIcon.AccessibleName = "ImgIcon";
            this.ImgIcon.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.ImgIcon.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ImgIcon.Image = global::QuillsModManagerV2.Properties.Resources.AnimatedQuillDiamond;
            this.ImgIcon.Location = new System.Drawing.Point(16, 12);
            this.ImgIcon.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.ImgIcon.MaximumSize = new System.Drawing.Size(30, 30);
            this.ImgIcon.MinimumSize = new System.Drawing.Size(30, 30);
            this.ImgIcon.Name = "ImgIcon";
            this.ImgIcon.Size = new System.Drawing.Size(30, 30);
            this.ImgIcon.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.ImgIcon.TabIndex = 15;
            this.ImgIcon.TabStop = false;
                                             this.BtnResetSettings.AccessibleDescription = "Reset all settings.";
            this.BtnResetSettings.AccessibleName = "BtnResetSettings";
            this.BtnResetSettings.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnResetSettings.Animated = true;
            this.BtnResetSettings.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(31)))));
            this.BtnResetSettings.CustomizableEdges.BottomLeft = false;
            this.BtnResetSettings.CustomizableEdges.BottomRight = false;
            this.BtnResetSettings.CustomizableEdges.TopLeft = false;
            this.BtnResetSettings.CustomizableEdges.TopRight = false;
            this.BtnResetSettings.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnResetSettings.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnResetSettings.FocusedColor = System.Drawing.Color.Gray;
            this.BtnResetSettings.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnResetSettings.ForeColor = System.Drawing.Color.White;
            this.BtnResetSettings.HoverState.FillColor = System.Drawing.Color.Gray;
            this.BtnResetSettings.Image = ((System.Drawing.Image)(resources.GetObject("BtnResetSettings.Image")));
            this.BtnResetSettings.Location = new System.Drawing.Point(506, 11);
            this.BtnResetSettings.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.BtnResetSettings.Name = "BtnResetSettings";
            this.BtnResetSettings.Size = new System.Drawing.Size(32, 32);
            this.BtnResetSettings.TabIndex = 11;
            this.BtnResetSettings.Click += new System.EventHandler(this.BtnResetSettings_Click);
                                             this.LabelTitle.AccessibleName = "LabelTitle";
            this.LabelTitle.AutoSize = true;
            this.LabelTitle.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.LabelTitle.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelTitle.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelTitle.Enabled = false;
            this.LabelTitle.Font = new System.Drawing.Font("Cascadia Code", 12F, System.Drawing.FontStyle.Bold);
            this.LabelTitle.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.LabelTitle.Location = new System.Drawing.Point(54, 16);
            this.LabelTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.LabelTitle.Name = "LabelTitle";
            this.LabelTitle.Size = new System.Drawing.Size(136, 21);
            this.LabelTitle.TabIndex = 12;
            this.LabelTitle.Text = "QMM / SETTINGS";
            this.LabelTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                             this.BtnClose.AccessibleName = "BtnClose";
            this.BtnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnClose.Animated = true;
            this.BtnClose.BackColor = System.Drawing.Color.Transparent;
            this.BtnClose.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(66)))));
            this.BtnClose.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnClose.CustomClick = true;
            this.BtnClose.CustomizableEdges.BottomLeft = false;
            this.BtnClose.CustomizableEdges.TopLeft = false;
            this.BtnClose.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnClose.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnClose.DataBindings.Add(new System.Windows.Forms.Binding("IconColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnClose.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnClose.HoverState.FillColor = System.Drawing.Color.Red;
            this.BtnClose.IconColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnClose.Location = new System.Drawing.Point(539, 11);
            this.BtnClose.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.BtnClose.MaximumSize = new System.Drawing.Size(37, 32);
            this.BtnClose.Name = "BtnClose";
            this.BtnClose.Size = new System.Drawing.Size(37, 32);
            this.BtnClose.TabIndex = 13;
            this.BtnClose.UseTransparentBackground = true;
            this.BtnClose.Click += new System.EventHandler(this.BtnClose_Click);
                                             this.PanelHeader.AccessibleName = "PanelHeader";
            this.PanelHeader.AutoSize = true;
            this.PanelHeader.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.PanelHeader.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelHeader.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelHeader.BorderThickness = 1;
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.PanelHeader.Enabled = false;
            this.PanelHeader.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.PanelHeader.Location = new System.Drawing.Point(10, 10);
            this.PanelHeader.Margin = new System.Windows.Forms.Padding(0);
            this.PanelHeader.MaximumSize = new System.Drawing.Size(0, 34);
            this.PanelHeader.MinimumSize = new System.Drawing.Size(0, 34);
            this.PanelHeader.Name = "PanelHeader";
            this.PanelHeader.Padding = new System.Windows.Forms.Padding(1);
            this.PanelHeader.Size = new System.Drawing.Size(567, 34);
            this.PanelHeader.TabIndex = 14;
                                             this.PanelBools.AccessibleName = "PanelBools";
            this.PanelBools.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PanelBools.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.PanelBools.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelBools.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelBools.BorderThickness = 1;
            this.PanelBools.Controls.Add(this.PanelContent);
            this.PanelBools.CustomizableEdges.TopLeft = false;
            this.PanelBools.CustomizableEdges.TopRight = false;
            this.PanelBools.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBools.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBools.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBools.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBools.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.PanelBools.Location = new System.Drawing.Point(286, 30);
            this.PanelBools.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.PanelBools.Name = "PanelBools";
            this.PanelBools.Padding = new System.Windows.Forms.Padding(9);
            this.PanelBools.Size = new System.Drawing.Size(270, 216);
            this.PanelBools.TabIndex = 23;
                                             this.PanelContent.AccessibleName = "PanelContent";
            this.PanelContent.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PanelContent.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.PanelContent.Controls.Add(this.vScroll);
            this.PanelContent.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelContent.Location = new System.Drawing.Point(11, 11);
            this.PanelContent.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.PanelContent.Name = "PanelContent";
            this.PanelContent.Size = new System.Drawing.Size(248, 194);
            this.PanelContent.TabIndex = 15;
                                             this.vScroll.AccessibleName = "vScroll";
            this.vScroll.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(36)))));
            this.vScroll.Dock = System.Windows.Forms.DockStyle.Right;
            this.vScroll.ForeColor = System.Drawing.Color.White;
            this.vScroll.LargeChange = 10;
            this.vScroll.Location = new System.Drawing.Point(236, 0);
            this.vScroll.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.vScroll.Maximum = 100;
            this.vScroll.Minimum = 0;
            this.vScroll.Name = "vScroll";
            this.vScroll.Size = new System.Drawing.Size(12, 194);
            this.vScroll.SmallChange = 1;
            this.vScroll.TabIndex = 14;
            this.vScroll.Value = 0;
                                             this.PanelBody.AccessibleName = "PanelBody";
            this.PanelBody.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PanelBody.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.PanelBody.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelBody.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelBody.BorderThickness = 1;
            this.PanelBody.Controls.Add(this.BtnChooseGamePath);
            this.PanelBody.Controls.Add(this.BtnChooseUserDataPath);
            this.PanelBody.Controls.Add(this.BtnChooseModPath);
            this.PanelBody.Controls.Add(this.TextBoxModPath);
            this.PanelBody.Controls.Add(this.TextBoxUserDataPath);
            this.PanelBody.Controls.Add(this.TextBoxGamePath);
            this.PanelBody.Controls.Add(this.BtnTheme);
            this.PanelBody.Controls.Add(this.PanelThemeHeader);
            this.PanelBody.Controls.Add(this.PanelTogglesHeader);
            this.PanelBody.Controls.Add(this.PanelBools);
            this.PanelBody.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBody.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBody.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBody.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBody.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.PanelBody.Location = new System.Drawing.Point(10, 54);
            this.PanelBody.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.PanelBody.Name = "PanelBody";
            this.PanelBody.Padding = new System.Windows.Forms.Padding(9);
            this.PanelBody.Size = new System.Drawing.Size(567, 257);
            this.PanelBody.TabIndex = 23;
                                             this.BtnChooseGamePath.AccessibleName = "BtnChooseGamePath";
            this.BtnChooseGamePath.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnChooseGamePath.Animated = true;
            this.BtnChooseGamePath.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.BtnChooseGamePath.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnChooseGamePath.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnChooseGamePath.BorderThickness = 1;
            this.BtnChooseGamePath.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnChooseGamePath.CustomizableEdges.BottomLeft = false;
            this.BtnChooseGamePath.CustomizableEdges.TopLeft = false;
            this.BtnChooseGamePath.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseGamePath.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseGamePath.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseGamePath.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseGamePath.DataBindings.Add(new System.Windows.Forms.Binding("PressedColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailActive", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseGamePath.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnChooseGamePath.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.BtnChooseGamePath.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.BtnChooseGamePath.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.BtnChooseGamePath.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnChooseGamePath.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnChooseGamePath.ForeColor = System.Drawing.Color.White;
            this.BtnChooseGamePath.Location = new System.Drawing.Point(239, 11);
            this.BtnChooseGamePath.Name = "BtnChooseGamePath";
            this.BtnChooseGamePath.PressedColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailActive;
            this.BtnChooseGamePath.Size = new System.Drawing.Size(37, 36);
            this.BtnChooseGamePath.TabIndex = 27;
            this.BtnChooseGamePath.Text = "...";
            this.BtnChooseGamePath.TextOffset = new System.Drawing.Point(0, -4);
            this.BtnChooseGamePath.Click += new System.EventHandler(this.BtnChoosePath_Click);
                                             this.BtnChooseUserDataPath.AccessibleName = "BtnChooseUserDataPath";
            this.BtnChooseUserDataPath.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnChooseUserDataPath.Animated = true;
            this.BtnChooseUserDataPath.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.BtnChooseUserDataPath.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnChooseUserDataPath.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnChooseUserDataPath.BorderThickness = 1;
            this.BtnChooseUserDataPath.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnChooseUserDataPath.CustomizableEdges.BottomLeft = false;
            this.BtnChooseUserDataPath.CustomizableEdges.TopLeft = false;
            this.BtnChooseUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("PressedColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailActive", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseUserDataPath.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnChooseUserDataPath.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.BtnChooseUserDataPath.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.BtnChooseUserDataPath.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.BtnChooseUserDataPath.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnChooseUserDataPath.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnChooseUserDataPath.ForeColor = System.Drawing.Color.White;
            this.BtnChooseUserDataPath.Location = new System.Drawing.Point(239, 57);
            this.BtnChooseUserDataPath.Name = "BtnChooseUserDataPath";
            this.BtnChooseUserDataPath.PressedColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailActive;
            this.BtnChooseUserDataPath.Size = new System.Drawing.Size(37, 36);
            this.BtnChooseUserDataPath.TabIndex = 27;
            this.BtnChooseUserDataPath.Text = "...";
            this.BtnChooseUserDataPath.TextOffset = new System.Drawing.Point(0, -4);
            this.BtnChooseUserDataPath.Click += new System.EventHandler(this.BtnChoosePath_Click);
                                             this.BtnChooseModPath.AccessibleName = "BtnChooseModPath";
            this.BtnChooseModPath.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnChooseModPath.Animated = true;
            this.BtnChooseModPath.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.BtnChooseModPath.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnChooseModPath.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnChooseModPath.BorderThickness = 1;
            this.BtnChooseModPath.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnChooseModPath.CustomizableEdges.BottomLeft = false;
            this.BtnChooseModPath.CustomizableEdges.TopLeft = false;
            this.BtnChooseModPath.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseModPath.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseModPath.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseModPath.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseModPath.DataBindings.Add(new System.Windows.Forms.Binding("PressedColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailActive", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnChooseModPath.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnChooseModPath.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.BtnChooseModPath.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.BtnChooseModPath.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.BtnChooseModPath.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnChooseModPath.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnChooseModPath.ForeColor = System.Drawing.Color.White;
            this.BtnChooseModPath.Location = new System.Drawing.Point(239, 103);
            this.BtnChooseModPath.Name = "BtnChooseModPath";
            this.BtnChooseModPath.PressedColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailActive;
            this.BtnChooseModPath.Size = new System.Drawing.Size(37, 36);
            this.BtnChooseModPath.TabIndex = 27;
            this.BtnChooseModPath.Text = "...";
            this.BtnChooseModPath.TextOffset = new System.Drawing.Point(0, -4);
            this.BtnChooseModPath.Click += new System.EventHandler(this.BtnChoosePath_Click);
                                             this.TextBoxModPath.AccessibleName = "TextBoxModPath";
            this.TextBoxModPath.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.TextBoxModPath.Animated = true;
            this.TextBoxModPath.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.TextBoxModPath.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.TextBoxModPath.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.TextBoxModPath.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxModPath.CustomizableEdges.BottomRight = false;
            this.TextBoxModPath.CustomizableEdges.TopRight = false;
            this.TextBoxModPath.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxModPath.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxModPath.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxModPath.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxModPath.DataBindings.Add(new System.Windows.Forms.Binding("PlaceholderForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "PlaceholderColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxModPath.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxModPath.DefaultText = "";
            this.TextBoxModPath.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.TextBoxModPath.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.TextBoxModPath.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TextBoxModPath.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TextBoxModPath.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.TextBoxModPath.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TextBoxModPath.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.TextBoxModPath.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.TextBoxModPath.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TextBoxModPath.Location = new System.Drawing.Point(11, 103);
            this.TextBoxModPath.Name = "TextBoxModPath";
            this.TextBoxModPath.PasswordChar = '\0';
            this.TextBoxModPath.PlaceholderForeColor = global::QuillsModManagerV2.Properties.Settings.Default.PlaceholderColor;
            this.TextBoxModPath.PlaceholderText = "Mod Library Path";
            this.TextBoxModPath.ReadOnly = true;
            this.TextBoxModPath.SelectedText = "";
            this.TextBoxModPath.Size = new System.Drawing.Size(229, 36);
            this.TextBoxModPath.TabIndex = 28;
                                             this.TextBoxUserDataPath.AccessibleName = "TextBoxUserDataPath";
            this.TextBoxUserDataPath.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.TextBoxUserDataPath.Animated = true;
            this.TextBoxUserDataPath.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.TextBoxUserDataPath.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.TextBoxUserDataPath.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.TextBoxUserDataPath.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxUserDataPath.CustomizableEdges.BottomRight = false;
            this.TextBoxUserDataPath.CustomizableEdges.TopRight = false;
            this.TextBoxUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("PlaceholderForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "PlaceholderColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxUserDataPath.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxUserDataPath.DefaultText = "";
            this.TextBoxUserDataPath.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.TextBoxUserDataPath.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.TextBoxUserDataPath.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TextBoxUserDataPath.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TextBoxUserDataPath.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.TextBoxUserDataPath.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TextBoxUserDataPath.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.TextBoxUserDataPath.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.TextBoxUserDataPath.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TextBoxUserDataPath.Location = new System.Drawing.Point(11, 57);
            this.TextBoxUserDataPath.Name = "TextBoxUserDataPath";
            this.TextBoxUserDataPath.PasswordChar = '\0';
            this.TextBoxUserDataPath.PlaceholderForeColor = global::QuillsModManagerV2.Properties.Settings.Default.PlaceholderColor;
            this.TextBoxUserDataPath.PlaceholderText = "User Data Path";
            this.TextBoxUserDataPath.ReadOnly = true;
            this.TextBoxUserDataPath.SelectedText = "";
            this.TextBoxUserDataPath.Size = new System.Drawing.Size(229, 36);
            this.TextBoxUserDataPath.TabIndex = 28;
                                             this.TextBoxGamePath.AccessibleName = "TextBoxGamePath";
            this.TextBoxGamePath.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.TextBoxGamePath.Animated = true;
            this.TextBoxGamePath.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.TextBoxGamePath.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.TextBoxGamePath.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.TextBoxGamePath.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxGamePath.CustomizableEdges.BottomRight = false;
            this.TextBoxGamePath.CustomizableEdges.TopRight = false;
            this.TextBoxGamePath.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxGamePath.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxGamePath.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxGamePath.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxGamePath.DataBindings.Add(new System.Windows.Forms.Binding("PlaceholderForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "PlaceholderColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxGamePath.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TextBoxGamePath.DefaultText = "";
            this.TextBoxGamePath.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.TextBoxGamePath.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.TextBoxGamePath.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TextBoxGamePath.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TextBoxGamePath.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.TextBoxGamePath.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TextBoxGamePath.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.TextBoxGamePath.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.TextBoxGamePath.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TextBoxGamePath.Location = new System.Drawing.Point(11, 11);
            this.TextBoxGamePath.Name = "TextBoxGamePath";
            this.TextBoxGamePath.PasswordChar = '\0';
            this.TextBoxGamePath.PlaceholderForeColor = global::QuillsModManagerV2.Properties.Settings.Default.PlaceholderColor;
            this.TextBoxGamePath.PlaceholderText = "Game Path";
            this.TextBoxGamePath.ReadOnly = true;
            this.TextBoxGamePath.SelectedText = "";
            this.TextBoxGamePath.Size = new System.Drawing.Size(229, 36);
            this.TextBoxGamePath.TabIndex = 28;
                                             this.BtnTheme.AccessibleName = "BtnTheme";
            this.BtnTheme.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnTheme.Animated = true;
            this.BtnTheme.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.BtnTheme.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnTheme.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnTheme.BorderThickness = 1;
            this.BtnTheme.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnTheme.CustomizableEdges.TopLeft = false;
            this.BtnTheme.CustomizableEdges.TopRight = false;
            this.BtnTheme.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnTheme.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnTheme.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnTheme.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnTheme.DataBindings.Add(new System.Windows.Forms.Binding("PressedColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailActive", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnTheme.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.BtnTheme.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.BtnTheme.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.BtnTheme.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.BtnTheme.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnTheme.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnTheme.ForeColor = System.Drawing.Color.White;
            this.BtnTheme.Image = ((System.Drawing.Image)(resources.GetObject("BtnTheme.Image")));
            this.BtnTheme.ImageSize = new System.Drawing.Size(64, 64);
            this.BtnTheme.Location = new System.Drawing.Point(11, 168);
            this.BtnTheme.Name = "BtnTheme";
            this.BtnTheme.PressedColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailActive;
            this.BtnTheme.Size = new System.Drawing.Size(265, 78);
            this.BtnTheme.TabIndex = 27;
            this.BtnTheme.Click += new System.EventHandler(this.BtnTheme_Click);
                                             this.PanelThemeHeader.AccessibleName = "PanelThemeHeader";
            this.PanelThemeHeader.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PanelThemeHeader.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.PanelThemeHeader.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelThemeHeader.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelThemeHeader.BorderThickness = 1;
            this.PanelThemeHeader.Controls.Add(this.LabelThemeTitle);
            this.PanelThemeHeader.CustomizableEdges.BottomLeft = false;
            this.PanelThemeHeader.CustomizableEdges.BottomRight = false;
            this.PanelThemeHeader.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelThemeHeader.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelThemeHeader.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelThemeHeader.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelThemeHeader.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.PanelThemeHeader.Location = new System.Drawing.Point(11, 149);
            this.PanelThemeHeader.Name = "PanelThemeHeader";
            this.PanelThemeHeader.Size = new System.Drawing.Size(265, 20);
            this.PanelThemeHeader.TabIndex = 26;
                                             this.LabelThemeTitle.AccessibleName = "LabelThemeTitle";
            this.LabelThemeTitle.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LabelThemeTitle.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.LabelThemeTitle.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelThemeTitle.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelThemeTitle.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LabelThemeTitle.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.LabelThemeTitle.Location = new System.Drawing.Point(21, 2);
            this.LabelThemeTitle.Name = "LabelThemeTitle";
            this.LabelThemeTitle.Size = new System.Drawing.Size(218, 15);
            this.LabelThemeTitle.TabIndex = 27;
            this.LabelThemeTitle.Text = "Theme Designer";
            this.LabelThemeTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
                                             this.PanelTogglesHeader.AccessibleName = "PanelTogglesHeader";
            this.PanelTogglesHeader.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.PanelTogglesHeader.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.PanelTogglesHeader.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelTogglesHeader.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelTogglesHeader.BorderThickness = 1;
            this.PanelTogglesHeader.Controls.Add(this.LabelTogglesTitle);
            this.PanelTogglesHeader.CustomizableEdges.BottomLeft = false;
            this.PanelTogglesHeader.CustomizableEdges.BottomRight = false;
            this.PanelTogglesHeader.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelTogglesHeader.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelTogglesHeader.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelTogglesHeader.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelTogglesHeader.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.PanelTogglesHeader.Location = new System.Drawing.Point(286, 11);
            this.PanelTogglesHeader.Name = "PanelTogglesHeader";
            this.PanelTogglesHeader.Size = new System.Drawing.Size(270, 20);
            this.PanelTogglesHeader.TabIndex = 26;
                                             this.LabelTogglesTitle.AccessibleName = "LabelTogglesTitle";
            this.LabelTogglesTitle.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.LabelTogglesTitle.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.LabelTogglesTitle.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelTogglesTitle.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelTogglesTitle.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LabelTogglesTitle.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.LabelTogglesTitle.Location = new System.Drawing.Point(26, 2);
            this.LabelTogglesTitle.Name = "LabelTogglesTitle";
            this.LabelTogglesTitle.Size = new System.Drawing.Size(218, 15);
            this.LabelTogglesTitle.TabIndex = 27;
            this.LabelTogglesTitle.Text = "Toggle Settings";
            this.LabelTogglesTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
                                             this.AccessibleName = "FormSettings";
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.ClientSize = new System.Drawing.Size(587, 321);
            this.Controls.Add(this.PanelBody);
            this.Controls.Add(this.ImgIcon);
            this.Controls.Add(this.BtnResetSettings);
            this.Controls.Add(this.LabelTitle);
            this.Controls.Add(this.BtnClose);
            this.Controls.Add(this.PanelHeader);
            this.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.Name = "FormSettings";
            this.Padding = new System.Windows.Forms.Padding(10);
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            this.Text = "FormSettings";
            ((System.ComponentModel.ISupportInitialize)(this.ImgIcon)).EndInit();
            this.PanelBools.ResumeLayout(false);
            this.PanelContent.ResumeLayout(false);
            this.PanelBody.ResumeLayout(false);
            this.PanelThemeHeader.ResumeLayout(false);
            this.PanelTogglesHeader.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Guna.UI2.WinForms.Guna2BorderlessForm FormSettingsEProperties;
        private System.Windows.Forms.PictureBox ImgIcon;
        private Guna.UI2.WinForms.Guna2Button BtnResetSettings;
        public Util.Controls.CClickThroughLabel LabelTitle;
        private Guna.UI2.WinForms.Guna2ControlBox BtnClose;
        private Guna.UI2.WinForms.Guna2Panel PanelHeader;
        private Guna.UI2.WinForms.Guna2Panel PanelBools;
        private System.Windows.Forms.Panel PanelContent;
        private Util.Controls.CustomVScrollBar vScroll;
        private Guna.UI2.WinForms.Guna2Panel PanelBody;
        private Guna.UI2.WinForms.Guna2Panel PanelTogglesHeader;
        private System.Windows.Forms.Label LabelTogglesTitle;
        private Guna.UI2.WinForms.Guna2Button BtnTheme;
        private Guna.UI2.WinForms.Guna2TextBox TextBoxGamePath;
        private Guna.UI2.WinForms.Guna2TextBox TextBoxUserDataPath;
        private Guna.UI2.WinForms.Guna2Panel PanelThemeHeader;
        private System.Windows.Forms.Label LabelThemeTitle;
        private Guna.UI2.WinForms.Guna2TextBox TextBoxModPath;
        private Guna.UI2.WinForms.Guna2Button BtnChooseGamePath;
        private Guna.UI2.WinForms.Guna2Button BtnChooseUserDataPath;
        private Guna.UI2.WinForms.Guna2Button BtnChooseModPath;
    }
}