namespace QuillsModManagerV2.UserControls
{
    partial class FormSettingsOLD
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormSettingsOLD));
            this.PanelHeader = new Guna.UI2.WinForms.Guna2Panel();
            this.ImgIcon = new System.Windows.Forms.PictureBox();
            this.BtnClose = new Guna.UI2.WinForms.Guna2ControlBox();
            this.ComboBoxThemes = new Guna.UI2.WinForms.Guna2ComboBox();
            this.TxtRoundAmount = new Guna.UI2.WinForms.Guna2TextBox();
            this.TxtColorInput = new Guna.UI2.WinForms.Guna2TextBox();
            this.BtnSetColor = new Guna.UI2.WinForms.Guna2Button();
            this.BtnSelectColor = new Guna.UI2.WinForms.Guna2Button();
            this.BtnToolTips = new Guna.UI2.WinForms.Guna2Button();
            this.BtnSave = new Guna.UI2.WinForms.Guna2Button();
            this.BtnResetSettings = new Guna.UI2.WinForms.Guna2Button();
            this.PanelBody = new Guna.UI2.WinForms.Guna2Panel();
            this.BtnEfficiencyMode = new Guna.UI2.WinForms.Guna2Button();
            this.BtnDebugMode = new Guna.UI2.WinForms.Guna2Button();
            this.BtnFormShadows = new Guna.UI2.WinForms.Guna2Button();
            this.ComboBoxChooseColor = new Guna.UI2.WinForms.Guna2ComboBox();
            this.BtnGamePath = new Guna.UI2.WinForms.Guna2Button();
            this.BtnAbout = new Guna.UI2.WinForms.Guna2Button();
            this.LabelTitle = new QuillsModManagerV2.Util.Controls.CClickThroughLabel();
            this.FormSettingsEProperties = new Guna.UI2.WinForms.Guna2BorderlessForm(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.ImgIcon)).BeginInit();
            this.PanelBody.SuspendLayout();
            this.SuspendLayout();
                                             this.PanelHeader.AccessibleName = "PanelHeader";
            this.PanelHeader.AutoSize = true;
            this.PanelHeader.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.PanelHeader.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelHeader.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelHeader.BorderThickness = 1;
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.PanelHeader.Enabled = false;
            this.PanelHeader.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.PanelHeader.Location = new System.Drawing.Point(10, 10);
            this.PanelHeader.Margin = new System.Windows.Forms.Padding(0);
            this.PanelHeader.MaximumSize = new System.Drawing.Size(0, 34);
            this.PanelHeader.MinimumSize = new System.Drawing.Size(0, 34);
            this.PanelHeader.Name = "PanelHeader";
            this.PanelHeader.Padding = new System.Windows.Forms.Padding(1);
            this.PanelHeader.Size = new System.Drawing.Size(602, 34);
            this.PanelHeader.TabIndex = 0;
                                             this.ImgIcon.AccessibleName = "ImgIcon";
            this.ImgIcon.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.ImgIcon.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ImgIcon.Image = global::QuillsModManagerV2.Properties.Resources.AnimatedQuillDiamond;
            this.ImgIcon.Location = new System.Drawing.Point(16, 12);
            this.ImgIcon.MaximumSize = new System.Drawing.Size(30, 30);
            this.ImgIcon.MinimumSize = new System.Drawing.Size(30, 30);
            this.ImgIcon.Name = "ImgIcon";
            this.ImgIcon.Size = new System.Drawing.Size(30, 30);
            this.ImgIcon.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.ImgIcon.TabIndex = 10;
            this.ImgIcon.TabStop = false;
                                             this.BtnClose.AccessibleName = "BtnClose";
            this.BtnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnClose.Animated = true;
            this.BtnClose.BackColor = System.Drawing.Color.Transparent;
            this.BtnClose.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(66)))));
            this.BtnClose.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnClose.CustomClick = true;
            this.BtnClose.CustomizableEdges.BottomLeft = false;
            this.BtnClose.CustomizableEdges.TopLeft = false;
            this.BtnClose.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnClose.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnClose.DataBindings.Add(new System.Windows.Forms.Binding("IconColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnClose.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnClose.HoverState.FillColor = System.Drawing.Color.Red;
            this.BtnClose.IconColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnClose.Location = new System.Drawing.Point(574, 11);
            this.BtnClose.MaximumSize = new System.Drawing.Size(37, 32);
            this.BtnClose.Name = "BtnClose";
            this.BtnClose.Size = new System.Drawing.Size(37, 32);
            this.BtnClose.TabIndex = 0;
            this.BtnClose.UseTransparentBackground = true;
            this.BtnClose.Click += new System.EventHandler(this.BtnClose_Click);
                                             this.ComboBoxThemes.AccessibleName = "ComboBoxThemes";
            this.ComboBoxThemes.BackColor = System.Drawing.Color.Transparent;
            this.ComboBoxThemes.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.ComboBoxThemes.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ComboBoxThemes.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ComboBoxThemes.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ComboBoxThemes.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ComboBoxThemes.DataBindings.Add(new System.Windows.Forms.Binding("FocusedColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailActive", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ComboBoxThemes.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.ComboBoxThemes.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.ComboBoxThemes.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.ComboBoxThemes.FocusedColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailActive;
            this.ComboBoxThemes.FocusedState.BorderColor = System.Drawing.Color.Cyan;
            this.ComboBoxThemes.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.ComboBoxThemes.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.ComboBoxThemes.HoverState.BorderColor = System.Drawing.Color.Red;
            this.ComboBoxThemes.ItemHeight = 39;
            this.ComboBoxThemes.Items.AddRange(new object[] {
            "Presets",
            "Default",
            "Default Light",
            "Simple Dark",
            "Simple Light",
            "Cosmos",
            "Rosé Pine",
            "Rosé Pine Moon",
            "Rosé Pine Dawn"});
            this.ComboBoxThemes.Location = new System.Drawing.Point(11, 121);
            this.ComboBoxThemes.Name = "ComboBoxThemes";
            this.ComboBoxThemes.Size = new System.Drawing.Size(108, 45);
            this.ComboBoxThemes.StartIndex = 0;
            this.ComboBoxThemes.TabIndex = 7;
            this.ComboBoxThemes.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.ComboBoxThemes.TextOffset = new System.Drawing.Point(13, 0);
            this.ComboBoxThemes.SelectedIndexChanged += new System.EventHandler(this.ComboBoxThemes_SelectedIndexChanged);
                                             this.TxtRoundAmount.AccessibleDescription = "The amount of pixels to round controls and forms by.";
            this.TxtRoundAmount.AccessibleName = "TxtRoundAmount";
            this.TxtRoundAmount.Animated = true;
            this.TxtRoundAmount.BackColor = System.Drawing.Color.Transparent;
            this.TxtRoundAmount.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.TxtRoundAmount.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.TxtRoundAmount.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtRoundAmount.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TxtRoundAmount.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TxtRoundAmount.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TxtRoundAmount.DataBindings.Add(new System.Windows.Forms.Binding("PlaceholderForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "PlaceholderColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TxtRoundAmount.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TxtRoundAmount.DefaultText = "";
            this.TxtRoundAmount.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.TxtRoundAmount.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.TxtRoundAmount.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TxtRoundAmount.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TxtRoundAmount.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.TxtRoundAmount.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(167)))), ((int)(((byte)(231)))));
            this.TxtRoundAmount.Font = new System.Drawing.Font("Gadugi", 9F);
            this.TxtRoundAmount.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.TxtRoundAmount.Location = new System.Drawing.Point(129, 121);
            this.TxtRoundAmount.MaxLength = 255;
            this.TxtRoundAmount.Name = "TxtRoundAmount";
            this.TxtRoundAmount.PasswordChar = '\0';
            this.TxtRoundAmount.PlaceholderForeColor = global::QuillsModManagerV2.Properties.Settings.Default.PlaceholderColor;
            this.TxtRoundAmount.PlaceholderText = "Roundedness";
            this.TxtRoundAmount.SelectedText = "";
            this.TxtRoundAmount.Size = new System.Drawing.Size(108, 45);
            this.TxtRoundAmount.TabIndex = 8;
            this.TxtRoundAmount.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.TxtRoundAmount.TextChanged += new System.EventHandler(this.TxtRoundAmount_TextChanged);
            this.TxtRoundAmount.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.TxtNumCheck_KeyPress);
            this.TxtRoundAmount.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.TxtColorInput.AccessibleDescription = "The hex value to use when setting colors.";
            this.TxtColorInput.AccessibleName = "TxtColorInput";
            this.TxtColorInput.Animated = true;
            this.TxtColorInput.BackColor = System.Drawing.Color.Transparent;
            this.TxtColorInput.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.TxtColorInput.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.TxtColorInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtColorInput.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TxtColorInput.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TxtColorInput.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TxtColorInput.DataBindings.Add(new System.Windows.Forms.Binding("PlaceholderForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "PlaceholderColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TxtColorInput.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TxtColorInput.DefaultText = "";
            this.TxtColorInput.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.TxtColorInput.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.TxtColorInput.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TxtColorInput.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.TxtColorInput.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.TxtColorInput.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(167)))), ((int)(((byte)(231)))));
            this.TxtColorInput.Font = new System.Drawing.Font("Gadugi", 9F);
            this.TxtColorInput.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.TxtColorInput.Location = new System.Drawing.Point(11, 11);
            this.TxtColorInput.MaxLength = 255;
            this.TxtColorInput.Name = "TxtColorInput";
            this.TxtColorInput.PasswordChar = '\0';
            this.TxtColorInput.PlaceholderForeColor = global::QuillsModManagerV2.Properties.Settings.Default.PlaceholderColor;
            this.TxtColorInput.PlaceholderText = "Color Input";
            this.TxtColorInput.SelectedText = "";
            this.TxtColorInput.Size = new System.Drawing.Size(108, 45);
            this.TxtColorInput.TabIndex = 1;
            this.TxtColorInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.TxtColorInput.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnSetColor.AccessibleDescription = "Set the chosen color.";
            this.BtnSetColor.AccessibleName = "BtnSetColor";
            this.BtnSetColor.Animated = true;
            this.BtnSetColor.BackColor = System.Drawing.Color.Transparent;
            this.BtnSetColor.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnSetColor.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnSetColor.BorderThickness = 1;
            this.BtnSetColor.CheckedState.CustomBorderColor = System.Drawing.Color.White;
            this.BtnSetColor.CheckedState.Font = new System.Drawing.Font("Gadugi", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnSetColor.CheckedState.ForeColor = System.Drawing.Color.White;
            this.BtnSetColor.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnSetColor.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSetColor.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSetColor.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSetColor.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSetColor.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnSetColor.Font = new System.Drawing.Font("Gadugi", 9F);
            this.BtnSetColor.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnSetColor.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(167)))), ((int)(((byte)(231)))));
            this.BtnSetColor.Location = new System.Drawing.Point(129, 66);
            this.BtnSetColor.Name = "BtnSetColor";
            this.BtnSetColor.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(36)))));
            this.BtnSetColor.Size = new System.Drawing.Size(108, 45);
            this.BtnSetColor.TabIndex = 5;
            this.BtnSetColor.Text = "Set Color";
            this.BtnSetColor.UseTransparentBackground = true;
            this.BtnSetColor.Click += new System.EventHandler(this.BtnSetColor_Click);
            this.BtnSetColor.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnSelectColor.AccessibleDescription = "Open the color selection form.";
            this.BtnSelectColor.AccessibleName = "BtnSelectColor";
            this.BtnSelectColor.Animated = true;
            this.BtnSelectColor.BackColor = System.Drawing.Color.Transparent;
            this.BtnSelectColor.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnSelectColor.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnSelectColor.BorderThickness = 1;
            this.BtnSelectColor.CheckedState.CustomBorderColor = System.Drawing.Color.White;
            this.BtnSelectColor.CheckedState.Font = new System.Drawing.Font("Gadugi", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnSelectColor.CheckedState.ForeColor = System.Drawing.Color.White;
            this.BtnSelectColor.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnSelectColor.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSelectColor.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSelectColor.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSelectColor.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSelectColor.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnSelectColor.Font = new System.Drawing.Font("Gadugi", 9F);
            this.BtnSelectColor.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnSelectColor.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(167)))), ((int)(((byte)(231)))));
            this.BtnSelectColor.Location = new System.Drawing.Point(129, 11);
            this.BtnSelectColor.Name = "BtnSelectColor";
            this.BtnSelectColor.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(36)))));
            this.BtnSelectColor.Size = new System.Drawing.Size(108, 45);
            this.BtnSelectColor.TabIndex = 2;
            this.BtnSelectColor.Text = "Select Color";
            this.BtnSelectColor.UseTransparentBackground = true;
            this.BtnSelectColor.Click += new System.EventHandler(this.BtnColor_Click);
            this.BtnSelectColor.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnToolTips.AccessibleDescription = "This popup message is a tooltip.\nIf you already know what things do, you don\'t ne" +
    "ed this.";
            this.BtnToolTips.AccessibleName = "BtnToolTips";
            this.BtnToolTips.Animated = true;
            this.BtnToolTips.BackColor = System.Drawing.Color.Transparent;
            this.BtnToolTips.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnToolTips.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnToolTips.BorderThickness = 1;
            this.BtnToolTips.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.ToogleButton;
            this.BtnToolTips.CheckedState.CustomBorderColor = System.Drawing.Color.White;
            this.BtnToolTips.CheckedState.Font = new System.Drawing.Font("Gadugi", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnToolTips.CheckedState.ForeColor = System.Drawing.Color.White;
            this.BtnToolTips.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnToolTips.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnToolTips.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnToolTips.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnToolTips.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnToolTips.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnToolTips.Font = new System.Drawing.Font("Gadugi", 9F);
            this.BtnToolTips.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnToolTips.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(167)))), ((int)(((byte)(231)))));
            this.BtnToolTips.Location = new System.Drawing.Point(248, 66);
            this.BtnToolTips.Name = "BtnToolTips";
            this.BtnToolTips.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(36)))));
            this.BtnToolTips.Size = new System.Drawing.Size(108, 45);
            this.BtnToolTips.TabIndex = 6;
            this.BtnToolTips.Text = "Tooltips";
            this.BtnToolTips.UseTransparentBackground = true;
            this.BtnToolTips.Click += new System.EventHandler(this.BtnToolTips_Click);
            this.BtnToolTips.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnSave.AccessibleDescription = "Save the current settings.";
            this.BtnSave.AccessibleName = "BtnSave";
            this.BtnSave.Animated = true;
            this.BtnSave.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(31)))));
            this.BtnSave.CustomizableEdges.BottomLeft = false;
            this.BtnSave.CustomizableEdges.BottomRight = false;
            this.BtnSave.CustomizableEdges.TopLeft = false;
            this.BtnSave.CustomizableEdges.TopRight = false;
            this.BtnSave.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnSave.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnSave.FocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(16)))), ((int)(((byte)(20)))));
            this.BtnSave.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnSave.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(16)))), ((int)(((byte)(20)))));
            this.BtnSave.HoverState.FillColor = System.Drawing.Color.Gray;
            this.BtnSave.Image = ((System.Drawing.Image)(resources.GetObject("BtnSave.Image")));
            this.BtnSave.ImageSize = new System.Drawing.Size(16, 16);
            this.BtnSave.Location = new System.Drawing.Point(541, 11);
            this.BtnSave.Name = "BtnSave";
            this.BtnSave.Size = new System.Drawing.Size(32, 32);
            this.BtnSave.TabIndex = 0;
            this.BtnSave.Click += new System.EventHandler(this.BtnSave_Click);
            this.BtnSave.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnResetSettings.AccessibleDescription = "Reset all settings.";
            this.BtnResetSettings.AccessibleName = "BtnResetSettings";
            this.BtnResetSettings.Animated = true;
            this.BtnResetSettings.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(31)))));
            this.BtnResetSettings.CustomizableEdges.BottomLeft = false;
            this.BtnResetSettings.CustomizableEdges.BottomRight = false;
            this.BtnResetSettings.CustomizableEdges.TopLeft = false;
            this.BtnResetSettings.CustomizableEdges.TopRight = false;
            this.BtnResetSettings.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnResetSettings.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnResetSettings.FocusedColor = System.Drawing.Color.Gray;
            this.BtnResetSettings.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnResetSettings.ForeColor = System.Drawing.Color.White;
            this.BtnResetSettings.HoverState.FillColor = System.Drawing.Color.Gray;
            this.BtnResetSettings.Image = ((System.Drawing.Image)(resources.GetObject("BtnResetSettings.Image")));
            this.BtnResetSettings.Location = new System.Drawing.Point(508, 11);
            this.BtnResetSettings.Name = "BtnResetSettings";
            this.BtnResetSettings.Size = new System.Drawing.Size(32, 32);
            this.BtnResetSettings.TabIndex = 0;
            this.BtnResetSettings.Click += new System.EventHandler(this.BtnResetSettings_Click);
            this.BtnResetSettings.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.PanelBody.AccessibleName = "PanelBody";
            this.PanelBody.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PanelBody.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.PanelBody.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.PanelBody.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.PanelBody.BorderThickness = 1;
            this.PanelBody.Controls.Add(this.TxtColorInput);
            this.PanelBody.Controls.Add(this.BtnEfficiencyMode);
            this.PanelBody.Controls.Add(this.BtnDebugMode);
            this.PanelBody.Controls.Add(this.BtnToolTips);
            this.PanelBody.Controls.Add(this.BtnFormShadows);
            this.PanelBody.Controls.Add(this.ComboBoxChooseColor);
            this.PanelBody.Controls.Add(this.ComboBoxThemes);
            this.PanelBody.Controls.Add(this.TxtRoundAmount);
            this.PanelBody.Controls.Add(this.BtnSelectColor);
            this.PanelBody.Controls.Add(this.BtnSetColor);
            this.PanelBody.Controls.Add(this.BtnGamePath);
            this.PanelBody.Controls.Add(this.BtnAbout);
            this.PanelBody.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBody.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBody.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBody.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGSecondary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PanelBody.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.BGSecondary;
            this.PanelBody.Location = new System.Drawing.Point(10, 54);
            this.PanelBody.Name = "PanelBody";
            this.PanelBody.Size = new System.Drawing.Size(602, 177);
            this.PanelBody.TabIndex = 0;
                                             this.BtnEfficiencyMode.AccessibleDescription = "Put the application in efficiency mode when running the game.";
            this.BtnEfficiencyMode.AccessibleName = "BtnEfficiencyMode";
            this.BtnEfficiencyMode.Animated = true;
            this.BtnEfficiencyMode.BackColor = System.Drawing.Color.Transparent;
            this.BtnEfficiencyMode.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnEfficiencyMode.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnEfficiencyMode.BorderThickness = 1;
            this.BtnEfficiencyMode.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.ToogleButton;
            this.BtnEfficiencyMode.CheckedState.CustomBorderColor = System.Drawing.Color.White;
            this.BtnEfficiencyMode.CheckedState.Font = new System.Drawing.Font("Gadugi", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnEfficiencyMode.CheckedState.ForeColor = System.Drawing.Color.White;
            this.BtnEfficiencyMode.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnEfficiencyMode.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnEfficiencyMode.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnEfficiencyMode.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnEfficiencyMode.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnEfficiencyMode.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnEfficiencyMode.Font = new System.Drawing.Font("Gadugi", 9F);
            this.BtnEfficiencyMode.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnEfficiencyMode.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(167)))), ((int)(((byte)(231)))));
            this.BtnEfficiencyMode.Location = new System.Drawing.Point(483, 11);
            this.BtnEfficiencyMode.Name = "BtnEfficiencyMode";
            this.BtnEfficiencyMode.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(36)))));
            this.BtnEfficiencyMode.Size = new System.Drawing.Size(108, 45);
            this.BtnEfficiencyMode.TabIndex = 10;
            this.BtnEfficiencyMode.Text = "Efficiency Mode";
            this.BtnEfficiencyMode.UseTransparentBackground = true;
            this.BtnEfficiencyMode.Click += new System.EventHandler(this.BtnEfficiencyMode_Click);
            this.BtnEfficiencyMode.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnDebugMode.AccessibleDescription = "Logs debug information, restart application for live console view.";
            this.BtnDebugMode.AccessibleName = "BtnDebugMode";
            this.BtnDebugMode.Animated = true;
            this.BtnDebugMode.BackColor = System.Drawing.Color.Transparent;
            this.BtnDebugMode.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnDebugMode.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnDebugMode.BorderThickness = 1;
            this.BtnDebugMode.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.ToogleButton;
            this.BtnDebugMode.CheckedState.CustomBorderColor = System.Drawing.Color.White;
            this.BtnDebugMode.CheckedState.Font = new System.Drawing.Font("Gadugi", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnDebugMode.CheckedState.ForeColor = System.Drawing.Color.White;
            this.BtnDebugMode.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnDebugMode.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnDebugMode.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnDebugMode.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnDebugMode.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnDebugMode.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnDebugMode.Font = new System.Drawing.Font("Gadugi", 9F);
            this.BtnDebugMode.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnDebugMode.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(167)))), ((int)(((byte)(231)))));
            this.BtnDebugMode.Location = new System.Drawing.Point(248, 11);
            this.BtnDebugMode.Name = "BtnDebugMode";
            this.BtnDebugMode.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(36)))));
            this.BtnDebugMode.Size = new System.Drawing.Size(108, 45);
            this.BtnDebugMode.TabIndex = 3;
            this.BtnDebugMode.Text = "Debug Mode";
            this.BtnDebugMode.UseTransparentBackground = true;
            this.BtnDebugMode.Click += new System.EventHandler(this.BtnDebugMode_Click);
            this.BtnDebugMode.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnFormShadows.AccessibleDescription = "The faded black \"shadow\" around forms.";
            this.BtnFormShadows.AccessibleName = "BtnFormShadows";
            this.BtnFormShadows.Animated = true;
            this.BtnFormShadows.BackColor = System.Drawing.Color.Transparent;
            this.BtnFormShadows.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnFormShadows.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnFormShadows.BorderThickness = 1;
            this.BtnFormShadows.ButtonMode = Guna.UI2.WinForms.Enums.ButtonMode.ToogleButton;
            this.BtnFormShadows.CheckedState.CustomBorderColor = System.Drawing.Color.White;
            this.BtnFormShadows.CheckedState.Font = new System.Drawing.Font("Gadugi", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnFormShadows.CheckedState.ForeColor = System.Drawing.Color.White;
            this.BtnFormShadows.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnFormShadows.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnFormShadows.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnFormShadows.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnFormShadows.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnFormShadows.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnFormShadows.Font = new System.Drawing.Font("Gadugi", 9F);
            this.BtnFormShadows.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnFormShadows.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(167)))), ((int)(((byte)(231)))));
            this.BtnFormShadows.Location = new System.Drawing.Point(248, 121);
            this.BtnFormShadows.Name = "BtnFormShadows";
            this.BtnFormShadows.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(36)))));
            this.BtnFormShadows.Size = new System.Drawing.Size(108, 45);
            this.BtnFormShadows.TabIndex = 9;
            this.BtnFormShadows.Text = "Color Border";
            this.BtnFormShadows.UseTransparentBackground = true;
            this.BtnFormShadows.Click += new System.EventHandler(this.BtnFormShadows_Click);
            this.BtnFormShadows.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.ComboBoxChooseColor.AccessibleDescription = "Choose which color to modify.";
            this.ComboBoxChooseColor.AccessibleName = "ComboBoxChooseColor";
            this.ComboBoxChooseColor.BackColor = System.Drawing.Color.Transparent;
            this.ComboBoxChooseColor.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.ComboBoxChooseColor.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ComboBoxChooseColor.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ComboBoxChooseColor.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ComboBoxChooseColor.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ComboBoxChooseColor.DataBindings.Add(new System.Windows.Forms.Binding("FocusedColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailActive", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ComboBoxChooseColor.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.ComboBoxChooseColor.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.ComboBoxChooseColor.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.ComboBoxChooseColor.FocusedColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailActive;
            this.ComboBoxChooseColor.FocusedState.BorderColor = System.Drawing.Color.Cyan;
            this.ComboBoxChooseColor.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.ComboBoxChooseColor.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.ComboBoxChooseColor.HoverState.BorderColor = System.Drawing.Color.Red;
            this.ComboBoxChooseColor.ItemHeight = 39;
            this.ComboBoxChooseColor.Items.AddRange(new object[] {
            "Select Color",
            "Primary Color",
            "Secondary Color",
            "Tertiary Color",
            "Detail Color",
            "Active Color",
            "Button Color",
            "Text Color",
            "Placeholder Color"});
            this.ComboBoxChooseColor.Location = new System.Drawing.Point(11, 66);
            this.ComboBoxChooseColor.Name = "ComboBoxChooseColor";
            this.ComboBoxChooseColor.Size = new System.Drawing.Size(108, 45);
            this.ComboBoxChooseColor.StartIndex = 0;
            this.ComboBoxChooseColor.TabIndex = 4;
            this.ComboBoxChooseColor.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.ComboBoxChooseColor.TextOffset = new System.Drawing.Point(13, 0);
                                             this.BtnGamePath.AccessibleDescription = "Set the path to your game folder.";
            this.BtnGamePath.AccessibleName = "BtnGamePath";
            this.BtnGamePath.Animated = true;
            this.BtnGamePath.BackColor = System.Drawing.Color.Transparent;
            this.BtnGamePath.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnGamePath.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnGamePath.BorderThickness = 1;
            this.BtnGamePath.CheckedState.CustomBorderColor = System.Drawing.Color.White;
            this.BtnGamePath.CheckedState.Font = new System.Drawing.Font("Gadugi", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnGamePath.CheckedState.ForeColor = System.Drawing.Color.White;
            this.BtnGamePath.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnGamePath.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnGamePath.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnGamePath.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnGamePath.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnGamePath.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnGamePath.Font = new System.Drawing.Font("Gadugi", 9F);
            this.BtnGamePath.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnGamePath.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(167)))), ((int)(((byte)(231)))));
            this.BtnGamePath.Location = new System.Drawing.Point(483, 66);
            this.BtnGamePath.Name = "BtnGamePath";
            this.BtnGamePath.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(36)))));
            this.BtnGamePath.Size = new System.Drawing.Size(108, 45);
            this.BtnGamePath.TabIndex = 11;
            this.BtnGamePath.Text = "Game Path";
            this.BtnGamePath.UseTransparentBackground = true;
            this.BtnGamePath.Click += new System.EventHandler(this.BtnGamePath_Click);
            this.BtnGamePath.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.BtnAbout.AccessibleDescription = "Some information on SE Edit.";
            this.BtnAbout.AccessibleName = "BtnAbout";
            this.BtnAbout.Animated = true;
            this.BtnAbout.BackColor = System.Drawing.Color.Transparent;
            this.BtnAbout.BorderColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailColor;
            this.BtnAbout.BorderRadius = global::QuillsModManagerV2.Properties.Settings.Default.BorderRadius;
            this.BtnAbout.BorderThickness = 1;
            this.BtnAbout.CheckedState.CustomBorderColor = System.Drawing.Color.White;
            this.BtnAbout.CheckedState.Font = new System.Drawing.Font("Gadugi", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnAbout.CheckedState.ForeColor = System.Drawing.Color.White;
            this.BtnAbout.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnAbout.DataBindings.Add(new System.Windows.Forms.Binding("FillColor", global::QuillsModManagerV2.Properties.Settings.Default, "ButtonColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnAbout.DataBindings.Add(new System.Windows.Forms.Binding("BorderRadius", global::QuillsModManagerV2.Properties.Settings.Default, "BorderRadius", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnAbout.DataBindings.Add(new System.Windows.Forms.Binding("BorderColor", global::QuillsModManagerV2.Properties.Settings.Default, "DetailColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnAbout.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BtnAbout.FillColor = global::QuillsModManagerV2.Properties.Settings.Default.ButtonColor;
            this.BtnAbout.Font = new System.Drawing.Font("Gadugi", 9F);
            this.BtnAbout.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.BtnAbout.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(167)))), ((int)(((byte)(231)))));
            this.BtnAbout.Location = new System.Drawing.Point(483, 121);
            this.BtnAbout.Name = "BtnAbout";
            this.BtnAbout.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(36)))));
            this.BtnAbout.Size = new System.Drawing.Size(108, 45);
            this.BtnAbout.TabIndex = 12;
            this.BtnAbout.Text = "About";
            this.BtnAbout.UseTransparentBackground = true;
            this.BtnAbout.Click += new System.EventHandler(this.BtnAbout_Click);
            this.BtnAbout.MouseEnter += new System.EventHandler(this.BtnToolTip_MouseEnter);
                                             this.LabelTitle.AccessibleName = "LabelTitle";
            this.LabelTitle.AutoSize = true;
            this.LabelTitle.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGTertiary;
            this.LabelTitle.DataBindings.Add(new System.Windows.Forms.Binding("ForeColor", global::QuillsModManagerV2.Properties.Settings.Default, "TextColor", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelTitle.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGTertiary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LabelTitle.Enabled = false;
            this.LabelTitle.Font = new System.Drawing.Font("Cascadia Code", 12F, System.Drawing.FontStyle.Bold);
            this.LabelTitle.ForeColor = global::QuillsModManagerV2.Properties.Settings.Default.TextColor;
            this.LabelTitle.Location = new System.Drawing.Point(48, 16);
            this.LabelTitle.Name = "LabelTitle";
            this.LabelTitle.Size = new System.Drawing.Size(136, 21);
            this.LabelTitle.TabIndex = 0;
            this.LabelTitle.Text = "QMM / SETTINGS";
            this.LabelTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                             this.FormSettingsEProperties.ContainerControl = this;
            this.FormSettingsEProperties.DockForm = false;
            this.FormSettingsEProperties.DockIndicatorTransparencyValue = 0.6D;
            this.FormSettingsEProperties.DragForm = false;
            this.FormSettingsEProperties.ResizeForm = false;
            this.FormSettingsEProperties.ShadowColor = global::QuillsModManagerV2.Properties.Settings.Default.DetailActive;
            this.FormSettingsEProperties.TransparentWhileDrag = true;
                                             this.AccessibleName = "FormSettings";
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = global::QuillsModManagerV2.Properties.Settings.Default.BGPrimary;
            this.ClientSize = new System.Drawing.Size(622, 241);
            this.Controls.Add(this.ImgIcon);
            this.Controls.Add(this.BtnResetSettings);
            this.Controls.Add(this.BtnSave);
            this.Controls.Add(this.LabelTitle);
            this.Controls.Add(this.BtnClose);
            this.Controls.Add(this.PanelHeader);
            this.Controls.Add(this.PanelBody);
            this.DataBindings.Add(new System.Windows.Forms.Binding("BackColor", global::QuillsModManagerV2.Properties.Settings.Default, "BGPrimary", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "FormSettingsOLD";
            this.Padding = new System.Windows.Forms.Padding(10);
            this.ShowIcon = false;
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            this.Text = "Settings";
            ((System.ComponentModel.ISupportInitialize)(this.ImgIcon)).EndInit();
            this.PanelBody.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Guna.UI2.WinForms.Guna2Panel PanelHeader;
        private System.Windows.Forms.PictureBox ImgIcon;
        private Guna.UI2.WinForms.Guna2ControlBox BtnClose;
        public Util.Controls.CClickThroughLabel LabelTitle;
        private Guna.UI2.WinForms.Guna2TextBox TxtColorInput;
        private Guna.UI2.WinForms.Guna2Button BtnSetColor;
        private Guna.UI2.WinForms.Guna2Button BtnSelectColor;
        private Guna.UI2.WinForms.Guna2Button BtnToolTips;
        private Guna.UI2.WinForms.Guna2ComboBox ComboBoxThemes;
        private Guna.UI2.WinForms.Guna2TextBox TxtRoundAmount;
        private Guna.UI2.WinForms.Guna2Button BtnSave;
        private Guna.UI2.WinForms.Guna2Button BtnResetSettings;
        private Guna.UI2.WinForms.Guna2Panel PanelBody;
        private Guna.UI2.WinForms.Guna2Button BtnFormShadows;
        private Guna.UI2.WinForms.Guna2Button BtnAbout;
        private Guna.UI2.WinForms.Guna2ComboBox ComboBoxChooseColor;
        private Guna.UI2.WinForms.Guna2Button BtnDebugMode;
        private Guna.UI2.WinForms.Guna2Button BtnGamePath;
        private Guna.UI2.WinForms.Guna2Button BtnEfficiencyMode;
        private Guna.UI2.WinForms.Guna2BorderlessForm FormSettingsEProperties;
    }
}